import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { access } from "node:fs/promises";
import { join } from "node:path";

const execFileAsync = promisify(execFile);

async function run(cmd: string, args: string[], cwd: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync(cmd, args, {
      cwd,
      maxBuffer: 10 * 1024 * 1024,
    });
    return stdout;
  } catch (err: unknown) {
    const e = err as { stdout?: string };
    if (e.stdout !== undefined) return e.stdout;
    return "";
  }
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

const AGENT_ICONS: Record<string, string> = {
  "Claude Code": "\uD83E\uDDE0",
  "Cursor": "\uD83D\uDDB1\uFE0F",
  "GitHub Copilot": "\uD83D\uDE80",
  "Aider": "\uD83D\uDC7E",
  "Windsurf": "\uD83C\uDFC4",
  "Unknown AI Agent": "\uD83E\uDD16",
};

export function getAgentIcon(agent: string): string {
  return AGENT_ICONS[agent] ?? "\uD83E\uDD16";
}

export async function detectAgent(cwd: string): Promise<string> {
  const signals: Record<string, number> = {
    "Claude Code": 0,
    "Cursor": 0,
    "GitHub Copilot": 0,
    "Aider": 0,
    "Windsurf": 0,
  };

  // 1. Check commit messages for co-author / signature patterns
  let log = "";
  try {
    log = await run("git", ["log", "--format=%B", "-20"], cwd);
  } catch {
    // ignore
  }

  if (log) {
    const lower = log.toLowerCase();

    // Co-Authored-By patterns
    if (/co-authored-by:.*claude/i.test(log)) signals["Claude Code"] += 3;
    if (/co-authored-by:.*copilot/i.test(log)) signals["GitHub Copilot"] += 3;
    if (/co-authored-by:.*cursor/i.test(log)) signals["Cursor"] += 3;

    // Tool signatures in commit body
    if (lower.includes("generated by claude") || lower.includes("claude code")) signals["Claude Code"] += 2;
    if (lower.includes("generated by copilot") || lower.includes("github copilot")) signals["GitHub Copilot"] += 2;
    if (lower.includes("generated by cursor") || lower.includes("cursor ai")) signals["Cursor"] += 2;
    if (/\baider\b/.test(lower)) signals["Aider"] += 3;
    if (lower.includes("windsurf")) signals["Windsurf"] += 2;
  }

  // 2. Check for tool-specific directories and files
  const checks: Array<[string, string]> = [
    [".claude", "Claude Code"],
    [".cursor", "Cursor"],
    [".github/copilot", "GitHub Copilot"],
    [".aider.conf.yml", "Aider"],
    [".aider.input.history", "Aider"],
    [".aiderignore", "Aider"],
    [".windsurfrules", "Windsurf"],
  ];

  const existChecks = checks.map(async ([path, agent]) => {
    if (await exists(join(cwd, path))) {
      signals[agent] += 2;
    }
  });
  await Promise.all(existChecks);

  // 3. Check git config for tool-specific settings
  let gitConfig = "";
  try {
    gitConfig = await run("git", ["config", "--list", "--local"], cwd);
  } catch {
    // ignore
  }

  if (gitConfig) {
    const lower = gitConfig.toLowerCase();
    if (lower.includes("claude")) signals["Claude Code"] += 1;
    if (lower.includes("copilot")) signals["GitHub Copilot"] += 1;
    if (lower.includes("cursor")) signals["Cursor"] += 1;
    if (lower.includes("aider")) signals["Aider"] += 1;
    if (lower.includes("windsurf")) signals["Windsurf"] += 1;
  }

  // Pick the agent with the highest signal score
  let best = "Unknown AI Agent";
  let bestScore = 0;

  for (const [agent, score] of Object.entries(signals)) {
    if (score > bestScore) {
      bestScore = score;
      best = agent;
    }
  }

  return best;
}
