import { writeFile } from "node:fs/promises";
import type { ReportData } from "./display.js";
import { getBranch } from "./git.js";

function getDateString(): string {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

export function generateMarkdown(data: ReportData, branch: string): string {
  const {
    parsedFiles,
    untrackedFiles,
    totalAdded,
    totalRemoved,
    newDeps,
    securityFlags,
    summary,
  } = data;

  const totalFiles = parsedFiles.length + untrackedFiles.length;
  const lines: string[] = [];

  lines.push("# whatdiditdo \u2014 AI Session Report");
  lines.push("");
  lines.push(`**Date:** ${getDateString()}`);
  lines.push(`**Branch:** ${branch}`);
  lines.push(
    `**Files changed:** ${totalFiles} | **+${totalAdded}** lines | **-${totalRemoved}** lines`
  );
  lines.push("");

  // Changes table
  lines.push("## Changes");
  lines.push("");
  lines.push("| File | Status | Changes |");
  lines.push("|------|--------|---------|");

  for (const f of parsedFiles) {
    if (f.isNew) {
      lines.push(`| ${f.file} | \u271A Added | +${f.added} lines |`);
    } else if (f.isDeleted) {
      lines.push(`| ${f.file} | \u2716 Deleted | -${f.removed} lines |`);
    } else {
      lines.push(`| ${f.file} | \u270E Modified | +${f.added} -${f.removed} |`);
    }
  }

  for (const f of untrackedFiles) {
    lines.push(`| ${f} | \u271A Added | untracked |`);
  }

  lines.push("");

  // New Dependencies
  if (newDeps.length > 0) {
    lines.push("## New Dependencies");
    for (const dep of newDeps) {
      lines.push(`- ${dep}`);
    }
    lines.push("");
  }

  // What Happened
  if (summary) {
    lines.push("## What Happened");
    lines.push(summary);
    lines.push("");
  }

  // Security Flags
  if (securityFlags.length > 0) {
    lines.push("## \u26A0\uFE0F Security Flags");
    for (const f of securityFlags) {
      const loc = f.line ? `${f.file}:${f.line}` : f.file;
      lines.push(`- \`${loc}\` \u2014 ${f.msg}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "*Generated by [whatdiditdo](https://github.com/peaktwilight/whatdiditdo)*"
  );
  lines.push("");

  return lines.join("\n");
}

export async function saveMarkdownReport(
  data: ReportData,
  cwd: string
): Promise<string> {
  const branch = await getBranch(cwd);
  const md = generateMarkdown(data, branch);
  const outPath = `${cwd}/whatdiditdo-report.md`;
  await writeFile(outPath, md, "utf-8");
  return outPath;
}
