import type { FileChange, SecurityFlag } from "./git.js";

export interface PRDescription {
  title: string;
  body: string;
}

export function generatePRDescription(
  files: FileChange[],
  newDeps: string[],
  securityFlags: SecurityFlag[],
  summary: string | null
): PRDescription {
  let title: string;

  if (summary) {
    // Take the first sentence of the AI summary as the title
    title = summary.split(/[.!?\n]/)[0].trim();
    if (title.length > 72) title = title.substring(0, 69) + "...";
  } else {
    // Generate title from file patterns
    const added = files.filter((f) => f.isNew);
    const modified = files.filter((f) => !f.isNew && !f.isDeleted);
    const deleted = files.filter((f) => f.isDeleted);

    if (added.length > 0 && modified.length === 0 && deleted.length === 0) {
      title = `Add ${added.map((f) => basename(f.file)).join(", ")}`;
    } else if (deleted.length > 0 && added.length === 0) {
      title = `Remove ${deleted.map((f) => basename(f.file)).join(", ")}`;
    } else {
      const totalAdd = files.reduce((s, f) => s + f.added, 0);
      const totalDel = files.reduce((s, f) => s + f.removed, 0);
      title = `Update ${files.length} file${files.length > 1 ? "s" : ""} (+${totalAdd} -${totalDel})`;
    }
    if (title.length > 72) title = title.substring(0, 69) + "...";
  }

  // Build PR body
  let body = "## Summary\n\n";

  if (summary) {
    body += summary + "\n\n";
  } else {
    body += `This PR modifies ${files.length} file${files.length > 1 ? "s" : ""}.\n\n`;
  }

  // Changes table
  body += "## Changes\n\n";
  body += "| File | Status | Changes |\n";
  body += "|------|--------|--------|\n";
  for (const f of files) {
    const icon = f.isNew ? "\u271A" : f.isDeleted ? "\u2716" : "\u270E";
    const status = f.isNew ? "added" : f.isDeleted ? "deleted" : "modified";
    const changes = f.isNew
      ? `+${f.added} lines`
      : f.isDeleted
        ? "removed"
        : `+${f.added} -${f.removed}`;
    body += `| ${icon} \`${f.file}\` | ${status} | ${changes} |\n`;
  }
  body += "\n";

  // New dependencies
  if (newDeps.length > 0) {
    body += "## New Dependencies\n\n";
    body += newDeps.map((d) => `- \`${d}\``).join("\n") + "\n\n";
  }

  // Security flags
  if (securityFlags.length > 0) {
    body += "## \u26A0\uFE0F Security Notes\n\n";
    body +=
      securityFlags
        .map((f) => {
          const loc = f.line ? `${f.file}:${f.line}` : f.file;
          return `- \`${loc}\` \u2014 ${f.msg}`;
        })
        .join("\n") + "\n\n";
  }

  // Test plan
  body += "## Test Plan\n\n";
  body += "- [ ] Reviewed changes\n";
  body += "- [ ] Tested locally\n";
  if (securityFlags.length > 0) body += "- [ ] Verified no secrets committed\n";
  if (newDeps.length > 0) body += "- [ ] Verified new dependencies\n";
  body +=
    "\n---\n*Generated by [whatdiditdo](https://github.com/peaktwilight/whatdiditdo)*\n";

  return { title, body };
}

function basename(path: string): string {
  return path.split("/").pop() || path;
}
